# Generated by Django 5.1.3 on 2024-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_contact_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('course_name', models.TextField()),
                ('img', models.FileField(upload_to='')),
                ('company', models.TextField()),
            ],
        ),
    ]
